---
stages:
  - Static Analysis
  - Tests
  - Release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv

default:
  image: node:latest
  interruptible: true

.python-job:
  image: python:latest
  before_script:
    - python --version ; pip --version 
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install -r requirements/dev.txt

# ============================================================================ #
#                                    Release                                   #
# ============================================================================ #


Semantic Release:
  stage: Release
  image: node:latest
  before_script:
    - npm install --save-dev conventional-changelog-conventionalcommits semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git @semantic-release/gitlab-config
  script:
    - npx semantic-release

# Update Repo:
#   stage: Release
#   needs:
#     - Semantic Release
#   script:
#     - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.laas.fr/rgodet1/tyr.git
#     - git add .
#     - git commit -m "chore(bump) version"
#     - git push gitlab_origin HEAD:$CI_COMMIT_REF_NAME -o ci.skip
